http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth:
    host: localhost
    paths:
      - '/v1/auth'
      - '/v1/auth/*'
  api:
    host: localhost
    paths: '/ip'
serviceEndpoints:
  authService:
    url: 'http://localhost:3000'
  httpbin:
    url: 'https://httpbin.org'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  authservice:
    apiEndpoints:
      - auth
    policies:
      - cors:
        - action:
            origin: '*'
      - proxy:
        - action:
            serviceEndpoint: authService
            changeOrigin: true
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
